sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Gz70vDXGD3eJzIuenJclzY17/4POJI4eeWfdIO4TM1D8l5wbIGPvoQ8eO/O3Rtvwi4zqFQS7LEx/Zws7SgoiWNkanS14VToZNquI0sJ2fbizROjj7dXeWjg7b5lXXQeofysqJby59xhCA6E9zH19r2hNwzoR96BVPfDDg+Cekgs79UDIeoPZt4aiIZzhnMbD38w/iX9Ph4Aotxpeoe6P35wCbgP7nOa0V7ADzU0jdz8HUj8yJQ+Wibb9VIGZmL0foH9iZ8Y2bKmrEquNRiKpQm/NPoMoMVZ8UWnTmBbBw3Gw1KzLq2/4QhzXxJLvLCt2Vi1GeGX9DnRe4A5seq5xogYcT0/WBbW7wZj2GEx/b6GAkNSN8c/arCi5D3+Tkuk3MJ6qvEzQvqcAnxav+7bTlfac+OLamQS8+Y6WD3/6thTRSRMs7G4KYqze75Co+bSiZ5Tnjpk6AAXND2YrWJTTUVVc2QQITsnaIMvEhxd3B519eb+cKMUx2BiTjNh8HvBReZ24HmDlkg1OiSMJoALovU0pMPNRqRDgGSNo+2SmTOFDW8O2Cszp8fi8cIHMM7OpuvweuSoExXZrxNgcVt1oxuJo+j4if3zBy9+ySDInT7JSQMK8lYSRa9eRp8yi14LYKi1LobdDc6Oc/8dcHZ0gmgIdmM+6YDQZdXdXst5IPRU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Odyssey-of-Homer-Done-into-English-Prose_1728
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy